### ISSUE TITLE
e-mail: iedereen kan naar iedereen in Chamilo een e-mail sturen

### ISSUE THREAD

**Issue by annickvdp** [annickvdp/Chamilo1.9.10#29]
dit moet beperkt worden door cursisten/docenten van de eigen cursussen

**Comment by ywarnier** [comment]
Actually, there is an option in the settings to change that behaviour to let you write only to your social network contacts.
But we're happy to check anything you send our way for review (as a Pull Request)

**Comment by annickvdp** [comment]
Thank you for your comment, but that's not a good solution for us as we do not really use the social network.  We want users to be able to contact ONLY those users that are in the same courses with them.

**Comment by ywarnier** [comment]
Annick, before you close this, could you give more details about where users can send mails to other students without the social network enabled?

**Comment by annickvdp** [comment]
Sorry, we do use the social network, but not the groups.

**Comment by ywarnier** [comment]
...and that makes it possible for users to send mails to others even if they are not in the same course? Through "friending" them on the social network?

**Comment by annickvdp** [comment]
II'm not sure which settings were enabled (a collegue fixed this issue).  All I know is that before ALL our users could send a message to ALL other users across the platform and now users can only send messages to users that are in a same course.

**Comment by ywarnier** [comment]
OK, seems OK then.
In general, if this is a code issue, try to send us the code, otherwise the issue will reappear in later versions :-)
